import type { Metadata } from "next";
import "./globals.css";
import './tailwind.css';
import {ReactNode} from "react";
import localFont from "next/font/local";
import {CookiesProvider} from "next-client-cookies/server";
import ProgressProvider from "@/components/providers/ProgressProvider";

export const metadata: Metadata = {
  title: "cher1sh-next-app",
  description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
  src: "../assets/fonts/pretendard.woff2",
  variable: "--font-prendard",
  weight: "100 900",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.variable}>
        <ProgressProvider>
          <CookiesProvider>
            <div className="w-full min-h-screen bg-bg">{children}</div>
          </CookiesProvider>
        </ProgressProvider>
      </body>
    </html>
  );
}
