import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import ToastContainer from "@/components/provider/ToastProvider";
import LoadingProvider from "@/components/provider/LoadingProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
    src: "../fonts/pretendard.woff2",
    variable: "--font-prendard",
    weight: "100 900",
    display: "swap",
  });

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <ToastContainer />
        <LoadingProvider color="black" />
        {children}
      </body>
    </html>
  );
}

export default RootLayout